### ISSUE TITLE
Make sure that zenoh-c api is fully covered by zenoh-cpp

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh-cpp#6]
Enums:

- [x] z_congestion_control_t
- [x] z_consolidation_mode_t
- [x] z_encoding_prefix_t
- [x] z_priority_t
- [x] z_query_target_t
- [x] z_reliability_t
- [x] z_sample_kind_t
- [x] z_encoding_prefix_t

Structs:

- [x] z_owned_session_t
- [x] z_query_t 
- [x] z_session_t
- [x] z_owned_pull_subscriber_t
- [x] z_owned_queryable_t
- [x] z_owned_subscriber_t
- [x] z_bytes_t
- [x] z_config_t
- [x] z_delete_options_t
- [x] z_encoding_t
- [x] z_get_options_t
- [x] z_hello_t
- [x] z_id_t
- [x] z_keyexpr_t
- [x] z_owned_closure_hello_t
- [x] z_owned_closure_query_t
- [x] z_owned_closure_reply_t
- [x] z_owned_closure_sample_t
- [x] z_owned_closure_zid_t
- [x] z_owned_config_t
- [ ] z_owned_encoding_t - https://github.com/eclipse-zenoh/zenoh-c/issues/110
- [x] z_owned_hello_t
- [x] z_owned_keyexpr_t
- [x] z_owned_publisher_t
- [x] z_owned_reply_channel_closure_t
- [x] z_owned_reply_channel_t
- [x] z_owned_reply_t
- [x] z_owned_scouting_config_t
- [ ] z_owned_str_array_t - https://github.com/eclipse-zenoh/zenoh-c/issues/110
- [x] z_publisher_delete_options_t
- [x] z_publisher_options_t
- [x] z_publisher_put_options_t
- [x] z_publisher_t
- [x] z_pull_subscriber_options_t
- [x] z_pull_subscriber_t
- [x] z_put_options_t
- [x] z_query_consolidation_t
- [x] z_query_reply_options_t
- [x] z_queryable_options_t
- [x] z_sample_t
- [x] z_str_array_t
- [x] z_subscriber_options_t
- [x] z_timestamp_t
- [x] z_value_t

Functions:

- [x] z_bytes_check
- [x] z_close
- [x] z_closure_hello_call
- [x] z_closure_hello_drop
- [x] z_closure_hello_null
- [x] z_closure_query_call
- [x] z_closure_query_drop
- [x] z_closure_query_null
- [x] z_closure_reply_call
- [x] z_closure_reply_drop
- [x] z_closure_reply_null
- [x] z_closure_sample_call
- [x] z_closure_sample_drop
- [x] z_closure_sample_null
- [x] z_closure_zid_call
- [x] z_closure_zid_drop
- [x] z_closure_zid_null
- [x] z_config_check
- [x] z_config_client
- [x] z_config_default
- [x] z_config_drop
- [x] z_config_loan
- [x] z_config_new - does the same as z_config_default, called by Config constructor
- [x] z_config_null
- [x] z_config_peer
- [x] z_declare_keyexpr
- [x] z_declare_publisher
- [x] z_declare_pull_subscriber
- [x] z_declare_queryable
- [x] z_declare_subscriber
- [x] z_delete
- [x] z_delete_options_default
- [x] z_encoding
- [ ] z_encoding_check - https://github.com/eclipse-zenoh/zenoh-c/issues/110
- [x] z_encoding_default
- [ ] z_encoding_drop - https://github.com/eclipse-zenoh/zenoh-c/issues/110
- [ ] z_encoding_loan - https://github.com/eclipse-zenoh/zenoh-c/issues/110
- [ ] z_encoding_null - https://github.com/eclipse-zenoh/zenoh-c/issues/110
- [x] z_get
- [x] z_get_options_default
- [x] z_hello_check
- [x] z_hello_drop
- [x] z_hello_loan
- [x] z_hello_null
- [x] z_info_peers_zid
- [x] z_info_routers_zid
- [x] z_info_zid
- [x] z_keyexpr
- [x] z_keyexpr_as_bytes
- [x] z_keyexpr_canonize
- [x] z_keyexpr_canonize_null_terminated - not necessary, C-specific
- [x] z_keyexpr_check
- [x] z_keyexpr_concat
- [x] z_keyexpr_drop
- [x] z_keyexpr_equals
- [x] z_keyexpr_includes
- [x] z_keyexpr_intersects
- [x] z_keyexpr_is_canon
- [x] z_keyexpr_is_initialized
- [x] z_keyexpr_join
- [x] z_keyexpr_loan
- [x] z_keyexpr_new
- [x] z_keyexpr_null
- [x] z_keyexpr_to_string - not necessary, C-specific
- [x] z_keyexpr_unchecked
- [x] z_open
- [x] z_publisher_check
- [x] z_publisher_delete
- [x] z_publisher_delete_options_default
- [x] z_publisher_loan
- [x] z_publisher_null
- [x] z_publisher_options_default
- [x] z_publisher_put
- [x] z_publisher_put_options_default
- [x] z_pull_subscriber_check
- [x] z_pull_subscriber_loan
- [x] z_pull_subscriber_null
- [x] z_pull_subscriber_options_default
- [x] z_put
- [x] z_put_options_default
- [x] z_query_consolidation_auto - not necessaty, just returns corresponding enum value
- [x] z_query_consolidation_default
- [x] z_query_consolidation_latest - not necessaty, just returns corresponding enum value
- [x] z_query_consolidation_monotonic - not necessaty, just returns corresponding enum value
- [x] z_query_consolidation_none - not necessaty, just returns corresponding enum value
- [x] z_query_keyexpr
- [x] z_query_parameters
- [x] z_query_reply
- [x] z_query_reply_options_default
- [x] z_query_target_default
- [x] z_query_value
- [x] z_queryable_check
- [x] z_queryable_null
- [x] z_queryable_options_default
- [x] z_reply_channel_closure_call
- [x] z_reply_channel_closure_drop
- [x] z_reply_channel_closure_null
- [x] z_reply_channel_drop
- [x] z_reply_channel_null
- [x] z_reply_check
- [x] z_reply_drop
- [x] z_reply_err
- [x] z_reply_is_ok
- [x] z_reply_null
- [x] z_reply_ok
- [x] z_scout
- [x] z_scouting_config_check
- [x] z_scouting_config_default
- [x] z_scouting_config_drop
- [x] z_scouting_config_from
- [x] z_scouting_config_null
- [x] z_session_check
- [x] z_session_loan
- [x] z_session_null
- [ ] z_str_array_check - https://github.com/eclipse-zenoh/zenoh-c/issues/110
- [ ] z_str_array_drop - https://github.com/eclipse-zenoh/zenoh-c/issues/110
- [ ] z_str_array_loan - https://github.com/eclipse-zenoh/zenoh-c/issues/110
- [x] z_subscriber_check
- [x] z_subscriber_null
- [x] z_subscriber_options_default
- [x] z_subscriber_pull
- [x] z_timestamp_check
- [x] z_undeclare_keyexpr
- [x] z_undeclare_publisher
- [x] z_undeclare_pull_subscriber
- [x] z_undeclare_queryable
- [x] z_undeclare_subscriber
- [x] zc_config_from_file
- [x] zc_config_from_str
- [x] zc_config_get
- [x] zc_config_insert_json
- [x] zc_config_to_string
- [x] zc_init_logger
- [x] zc_keyexpr_from_slice
- [x] zc_keyexpr_from_slice_unchecked
- [x] zc_reply_fifo_new
- [x] zc_reply_non_blocking_fifo_new
